spring:
  application:
    name: accountservice
  datasource:
    url: jdbc:mysql://mysql:3306/accountdb
    username: root
    password: Orthopoda@2947
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

customer:
  service:
    endpoint: http://customerservice/customers/
microservice:
  deployment:
    rfc: RFC-9023


server:
  port: 8081
